"use server";

import { actionClient } from "@/lib/safe-action";
import { db } from "@/lib/db";
import { movie } from "@/lib/db/schema";
import { desc } from "drizzle-orm";
import { flattenValidationErrors } from "next-safe-action";
import type { InferInsertModel } from "drizzle-orm";
import { randomUUID } from "crypto";

// Validation Schemas
import { createMovieSchema } from "@/lib/validation/movies";

export const getAllMovies = actionClient
  .metadata({ actionName: "getAllMovies" })
  .action(async () => {
    const movies = await db.query.movie.findMany();

    return movies;
  });

export const createMovie = actionClient
  .metadata({ actionName: "createMovie" })
  .inputSchema(createMovieSchema, {
    handleValidationErrorsShape: async (errors) => {
      return flattenValidationErrors(errors).fieldErrors;
    },
  })
  .action(async ({ parsedInput }) => {
    // createdAt and updatedAt are auto-generated by the database
    const insertData: InferInsertModel<typeof movie> = {
      id: randomUUID(),
      title: parsedInput.title,
      description: parsedInput.description || null,
      image: parsedInput.image || null,
    };

    const [newMovie] = await db.insert(movie).values(insertData).returning();

    return {
      movie: newMovie,
      message: "Película creada correctamente.",
    };
  });
